language: python

python:
  - '2.7'
sudo: required

cache:
  - docker

services:
  - docker

install:
  - sudo pip install --upgrade pip
  - sudo pip install coveralls

script:
  - export CURRENT_PATH=`pwd`
  - docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter-ws /bin/bash -c "cd  $CURRENT_PATH && coverage run -m unittest discover hepdata_converter/testsuite 'test_*'"
  - docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter-ws /bin/bash -c "cd  $CURRENT_PATH && python setup.py install && hepdata-converter -v"

after_success:
  - coveralls

